# General Jekyll Config
pygments: true
url: http://diego.curbelo.com
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore]

# Theme customization - please change from the defaults!
theme:
  # Color for top bar, links, etc
  highlight_color: '#3498db'

  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: diegocurbelo
    bitbucket: diegocurbelo
    #hacker_news: diegocurbelo
    #stackexchange: 348619
    #stackoverflow: 348619
    twitter: diegocurbelo
    #facebook: zuck
    #tumblr: animalygifs
    #linkedin: philipjagielski
    #gplus: 110552447039675960964

  # "Hi, I'm _______"
  name: Diego Curbelo
  email: diego@curbelo.com
  tagline: "Geeky notes"

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-26816256-1

  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: false
